FROM mongo


COPY keyfile.txt /
RUN chmod 400 /keyfile.txt
RUN chown 999:999 /keyfile.txt
CMD ["--keyFile", "/keyfile.txt", "--shardsvr","--replSet", "shardrepl1" ]
VOLUME [ "/data" ]
EXPOSE 27018:27018