FROM mongodb/mongodb-community-server

USER root
COPY keyfile.txt /
COPY mongod.conf /etc
#RUN chown mongodb:mongodb /keyfile.txt
RUN chmod 400 /keyfile.txt
RUN chown mongodb:mongodb /keyfile.txt
USER mongodb
VOLUME [ "/data" ]
CMD ["--config", "/etc/mongod.conf" ]
EXPOSE 27017:27017